# Schur polynomials and RSK

## Math 737 - Lab 5

## Exercise 1: Evaluate the blocks below to see how to work with the built-in Schur polynomial function in Sage.
- ### Try changing the parameters $[2,1]$ and $3$ to see what this does to the polynomial.
- ### Fill in the blank in the 'for' loop to display the appropriate tableaux that correspond to the polynomial for the parameters $[2,1]$ and $3$.

In [30]:
from IPython.display import Math, display
#-------------- jupyter doesnt display sage objects properly unless I make it do it myself so yeah -----------------------
def dplay(x):
    return display(Math(latex(x)))
#-------------------------------------------------------

s = SymmetricFunctions(QQ).s()
print("([2,1],3): Original")
dplay((s([2,1]).expand(3)))
print("([3,1],3)")
dplay((s([3,1]).expand(3)))
print("([2,2],3)")
dplay((s([2,2]).expand(3)))
print("([2,1],4)")
dplay(s([2,1]).expand(4))



([2,1],3): Original


<IPython.core.display.Math object>

([3,1],3)


<IPython.core.display.Math object>

([2,2],3)


<IPython.core.display.Math object>

([2,1],4)


<IPython.core.display.Math object>

This finds the Schur polynomial of the SSYT {left parameter} in {right parameter} variables

In [3]:
for tab in SemistandardTableaux([2,1], max_entry=3):
    display(tab)
    print('------')

------


------


------


------


------


------


------


------


## Exercise 2: Use the above code for the Schur polynomial to test an example of the Pieri rule.
- ### First, calculate the two Schur polynomials you are multiplying together on the LHS of the Pieri rule.
- ### Then use the method on partitions add_horizontal_border_strip or add_vertical_border_strip to create all the partitions for the Schur polynomials on the RHS. Calculate these Schur polynomials and add them together.
- ### Check that your computations for the LHS and RHS agree.

In [31]:
s([1])*s([1])

s[1, 1] + s[2]

In [32]:
p = Partition([4,2,1])
p.add_horizontal_border_strip(2)

[[6, 2, 1],
 [5, 3, 1],
 [5, 2, 2],
 [5, 2, 1, 1],
 [4, 4, 1],
 [4, 3, 2],
 [4, 3, 1, 1],
 [4, 2, 2, 1]]

I do s([1])*s([2]) below:

In [39]:
s = SymmetricFunctions(QQ).s()

LHS = s([1]) * s([2])

RHS_parts = Partition([1]).add_horizontal_border_strip(2)

RHS = sum(s(mu) for mu in parts)

print("LHS:")
dis(LHS)

print("Partitions:")
print(parts)

print("RHS:")
dis(RHS)

print(f"It is {LHS == RHS} that LHS=RHS.")

LHS:


<IPython.core.display.Math object>

Partitions:
[[3], [2, 1]]
RHS:


<IPython.core.display.Math object>

It is True that LHS=RHS.


## Exercise 3:
- ### Google search the phrase 'sage math rsk' to find the Sage documentation for the RSK and RSK_inverse functions.
- ### Then create one or more examples (different from the examples in the documentation) to demonstrate how to use these functions. One of your examples should check you work on the Team Activity from the end of Wednesday's class.
- ### Demonstrate in your examples what happens to the matrix when you swap the tableaux P and Q.

In [63]:
sigma = Permutation([3,1,4,2])

P, Q = RSK(perm)
print("Insertion Tableau P:")
display(P)
print("Recording Tableau Q:")
display(Q)
print("Inverse permutation of RSK(P,Q):")
print(RSK_inverse(P, Q, output='permutation'))
print("Inverse permutation of RSK(Q,P):")
print(RSK_inverse(Q, P, output='permutation'))
print(f"It is {RSK_inverse(Q, P, output='permutation') == sigma.inverse()} that RSK_inverse(Q,P)=(3142)^-1=(2413)")


Insertion Tableau P:


Recording Tableau Q:


Inverse permutation of RSK(P,Q):
[3, 1, 4, 2]
Inverse permutation of RSK(Q,P):
[2, 4, 1, 3]
It is True that RSK_inverse(Q,P)=(3142)^-1=(2413)


For  the permutation $(3142)$, RSK gives an insertion tableau P and recording tableau Q. RSK_inverse(P,Q) recovers $(3142)$ once more. Then when P and Q are swapped, RSK_inverse(Q,P) gives the inverse $(3142)^{-1}=(2413)$ as expected.

In [70]:
M = Matrix([[0,1,0],
            [2,0,1],
            [0,1,1]])
print("M:")
P, Q = RSK(M)
dplay(M)
print("P:")
display(P)
print("Q:")
display(Q)

M:


<IPython.core.display.Math object>

P:


Q:


In [77]:
print("RSK_inverse(P,Q):")
dplay(RSK_inverse(P, Q, output='matrix'))
print("M once more:")
dplay(M)
print("RSK_inverse(Q,P):")
dplay(RSK_inverse(Q, P, output='matrix'))
print("M^{T}:")
dplay(M.transpose())
print(f"It is {RSK_inverse(Q, P, output='matrix') == M.transpose()} that RSK_inverse(Q,P)=M^T.")

RSK_inverse(P,Q):


<IPython.core.display.Math object>

M once more:


<IPython.core.display.Math object>

RSK_inverse(Q,P):


<IPython.core.display.Math object>

M^{T}:


<IPython.core.display.Math object>

It is True that RSK_inverse(Q,P)=M^T.


## Exercise 4: Finish the 'for' loop below to check that for every involution of $S_3$, its corresponding insertion and recording tableaux are equal. Do the same for $n=4,5,6$.

In [87]:
invcount = 0
eqcount = 0

for i in [3,4,5,6]:
    for sigma in Permutations(i):
        if sigma == sigma.inverse():
            invcount += 1
            P, Q = RSK(sigma)
            eqcount += int(P==Q)
    dplay(f"It is {invcount==eqcount} that for every involution of S_{i}, its corresponding insertion and recording tableaux are equal")


<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

You can see the loop above checks that statement given for $S_{3},\dots,S_{6}$ by counting the number of inversions and inversions where the statement holds and then comparing the two at the end.

## Exercise 5: Calculate the sum of $(f^{\lambda})^2$ for all $\lambda$ with $3$ boxes. Do the same for $n=4,5,6$. Conjecture a formula in terms of $n$. How does RSK prove this formula? (The answer is in Section 4.3.)

In [95]:
for i in [3,4,5,6]:
    totsum = 0

    for labda in Partitions(i):
        f = StandardTableaux(labda).cardinality()
        totsum = totsum + f^2

    print(f"It is {totsum == factorial(i)} that {i}! = Sum of (f^lambda)^2 for all lambda with {i} boxes.")

It is True that 3! = Sum of (f^lambda)^2 for all lambda with 3 boxes.
It is True that 4! = Sum of (f^lambda)^2 for all lambda with 4 boxes.
It is True that 5! = Sum of (f^lambda)^2 for all lambda with 5 boxes.
It is True that 6! = Sum of (f^lambda)^2 for all lambda with 6 boxes.


RSK proves this because it gives a correspondence between permutations $\sigma\in S_{n}$ to pairs $(P,Q)$ of standard young tableau of the same shape $\lambda\vdash n$. (I am assuming we proved this but if not, we saw that there exists a bijective inverse for the mapping earlier in the lab.) So of course the number $(f^{\lambda})^{2}$ of such pairs is equal to the number of such permutations $\sigma\in S_{n}$. That is:
$$(f^{\lambda})^{2}= |S_{n}|=n!$$